"""Added gender to pet table

Revision ID: 0e638bd48c63
Revises: 44c1ef6f7ba3
Create Date: 2025-05-31 20:43:20.048219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e638bd48c63'
down_revision: Union[str, None] = '44c1ef6f7ba3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('Gender', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pets', 'Gender')
    # ### end Alembic commands ###
