"""Initial tables

Revision ID: 1780a6b534d5
Revises: 
Create Date: 2025-06-04 14:58:41.504368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1780a6b534d5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pets')
    op.drop_table('clinics')
    op.drop_table('appointments')
    op.drop_table('clinic_pet_visits')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinic_pet_visits',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('visit_date', sa.DATE(), nullable=True),
    sa.Column('notes', sa.VARCHAR(), nullable=True),
    sa.Column('pet_id', sa.INTEGER(), nullable=True),
    sa.Column('clinic_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pet_id', sa.INTEGER(), nullable=True),
    sa.Column('clinic_id', sa.INTEGER(), nullable=True),
    sa.Column('appointment_time', sa.DATETIME(), nullable=True),
    sa.Column('reason', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clinics',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('address', sa.VARCHAR(), nullable=False),
    sa.Column('phone', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pets',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('species', sa.VARCHAR(), nullable=False),
    sa.Column('breed', sa.VARCHAR(), nullable=True),
    sa.Column('age', sa.INTEGER(), nullable=False),
    sa.Column('owner_name', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
